package com.solutions.shop.model;

import lombok.Data;

import javax.persistence.*;

@Data
@Entity
@Table(name = "user", schema = "public")
public class User {
    @Id
    @Column(name = "user_id")
    Integer userId;

    @Column(name = "password")
    String password;

    @Column(name = "role")
    String role;

    public Integer getId() {
        return userId;
    }

    /* GET SET methods are generated by lombok. All fields are private. */
}
