package com.solutions.shop.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;

import lombok.Data;

@Data
@Entity
@Table(name = "users")
public class Users {
    @Id
    @Column(name = "login")
    @NotBlank
    String login;

    @Column(name = "password")
    @NotBlank
    String password;

    public @NotBlank String getId() {
        return login;
    }

    /* GET SET methods are generated by lombok. All fields are private. */
}
