package com.solutions.shop.model;

import lombok.Data;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;

@Data
@Entity
@Table(name = "users")
public class Users {
    @Id
    @Column(name = "user_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    Integer userId;

    @Column(name = "password")
    @NotBlank
    String password;

    @Column(name = "role")
    String role;

    public Integer getId() {
        return userId;
    }

    /* GET SET methods are generated by lombok. All fields are private. */
}
