CREATE TABLE IF NOT EXISTS shopping_cart (
  order_id INT NOT NULL PRIMARY KEY,
  customer_id INT NOT NULL,
  confirmed_y_n boolean NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_product (
  order_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  product_id INT NOT NULL,
  PRIMARY KEY(order_id, product_id),
  FOREIGN KEY (order_id) REFERENCES shopping_cart (order_id),
  FOREIGN KEY (product_id) REFERENCES product (product_id)
);