CREATE TABLE IF NOT EXISTS shoppingСart (
  order_id INT NOT NULL PRIMARY KEY,
  customer_id INT NOT NULL,
  confirmed_y_n boolean NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orderProduct (
  order_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  product_id INT NOT NULL,
  PRIMARY KEY(order_id, product_id),
  FOREIGN KEY (order_id) REFERENCES shoppingСart (order_id),
  FOREIGN KEY (product_id) REFERENCES product (product_id)
);