DROP TABLE IF EXISTS order_product;
DROP TABLE IF EXISTS shopping_cart;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS product;

-- seq_user was created in Script 0006

CREATE TABLE IF NOT EXISTS users (
  user_id INT DEFAULT nextval('seq_user') NOT NULL,
  login VARCHAR(30) NOT NULL UNIQUE,
  password VARCHAR(70) NOT NULL,
  PRIMARY KEY(user_id)
);

CREATE TABLE IF NOT EXISTS customer (
  customer_id INT NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  address VARCHAR(255) NOT NULL,
  PRIMARY KEY(customer_id),
  FOREIGN KEY (customer_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE SEQUENCE seq_product
minvalue 1
start with 1
increment by 1;

create table IF NOT EXISTS product (
    product_id INT DEFAULT nextval('seq_product') NOT NULL,
    name varchar(20) NOT NULL,
    description varchar(255) NOT NULL,
    price DECIMAL NOT NULL,
    brand varchar(255) NOT NULL,
    category varchar(255) NOT NULL,
    primary key (product_id)
);

CREATE TABLE IF NOT EXISTS shopping_cart (
  order_id INT NOT NULL PRIMARY KEY,
  customer_id INT NOT NULL,
  confirmed boolean NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_product (
  order_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  product_id INT NOT NULL,
  PRIMARY KEY(order_id, product_id),
  FOREIGN KEY (order_id) REFERENCES shopping_cart (order_id),
  FOREIGN KEY (product_id) REFERENCES product (product_id)
);