CREATE TABLE IF NOT EXISTS customer (
  customer_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  address VARCHAR(255) NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES users (user_id) ON DELETE CASCADE
);

create table IF NOT EXISTS product (
    product_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(20) NOT NULL,
    description varchar(255) NOT NULL,
    price DECIMAL NOT NULL,
    brand varchar(255) NOT NULL,
    category varchar(255) NOT NULL,
    primary key (product_id)
);